name = "marius-terminal"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "Terminal-inspired, minimal Hugo theme with dark mode and faux prompt line. Now with heroes + link inversion."
homepage = "https://example.com"
tags = ["minimal", "blog", "terminal", "dark"]
features = ["dark mode", "promptline", "pagination", "menus", "hero images"]
min_version = "0.115.0"

[author]
  name = "You"
  homepage = "https://example.com"